import{a as y,S as L,i as c}from"./assets/vendor-CNqCr-V-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const b="https://pixabay.com/api/",w="51217923-e424984f9b43f1bcfdccd2a18";async function S(r,t){const s={key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await y.get(b,{params:s})).data}const d=document.querySelector(".gallery"),u=document.querySelector(".loader"),f=document.querySelector(".load-more"),q=new L(".gallery a",{captionsData:"alt",captionDelay:250});function v(r){const t=r.map(({webformatURL:s,largeImageURL:n,tags:e,likes:o,views:i,comments:h,downloads:g})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${n}">
          <img class="gallery-image" src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${i}</p>
          <p><b>Comments</b> ${h}</p>
          <p><b>Downloads</b> ${g}</p>
        </div>
      </li>
    `).join("");d.insertAdjacentHTML("beforeend",t),q.refresh()}function P(){d.innerHTML=""}function E(){u.classList.remove("is-hidden")}function M(){u.classList.add("is-hidden")}function B(){f.classList.remove("is-hidden")}function l(){f.classList.add("is-hidden")}const $=document.querySelector(".form"),A=document.querySelector(".load-more");let m="",a=1;const R=15;$.addEventListener("submit",O);A.addEventListener("click",_);async function O(r){r.preventDefault();const t=r.currentTarget.elements.searchQuery.value.trim();if(!t){c.warning({message:"Please enter a search term!",position:"topRight"});return}m=t,a=1,P(),l(),await p()}async function _(){a+=1,await p(!0)}async function p(r=!1){E();try{const t=await S(m,a),{hits:s,totalHits:n}=t;if(!s||s.length===0){a===1&&c.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l();return}v(s);const e=Math.ceil(n/R);a<e?B():(l(),c.info({message:"You've reached the end of search results.",position:"topRight"})),r&&x()}catch{c.error({message:"An error occurred during the request. Please try again.",position:"topRight"})}finally{M()}}function x(){const r=document.querySelector(".gallery-item");if(!r)return;const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
